version: "3"
services:
    mysqlsrv:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "RootPassword!"
            MYSQL_DATABASE: "testedb"
        ports:
            - "3306:3306"
        volumes:
            - /d/Docker/Volumes/MySql:/var/lib/mysql
        networks:
            - mysql-network

    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - mysql-network
    
networks: 
    mysql-network:
        driver: bridge