version: "3"
services:
    sqlserver:
        container_name: sqlserver
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "saPassword!"
            ACCEPT_EULA: "Y"